// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9RqDRgPAmWL_MyJQMS-P6yT2vL3jULGk',
    appId: '1:6293016505:web:71bc3deac4f31f7523f068',
    messagingSenderId: '6293016505',
    projectId: 'gacha-guard',
    authDomain: 'gacha-guard.firebaseapp.com',
    storageBucket: 'gacha-guard.firebasestorage.app',
    measurementId: 'G-XB0CR6M9NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBpgNzMDA-qllCVEXmNl1WAThk4rJ9-l4',
    appId: '1:6293016505:android:b3873f12198b3f4623f068',
    messagingSenderId: '6293016505',
    projectId: 'gacha-guard',
    storageBucket: 'gacha-guard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N05wC4TCbtSQTzgsVGPh2K-0OwW5m7Q',
    appId: '1:6293016505:ios:1a35086fdbeb65ec23f068',
    messagingSenderId: '6293016505',
    projectId: 'gacha-guard',
    storageBucket: 'gacha-guard.firebasestorage.app',
    iosBundleId: 'com.example.gachaGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5N05wC4TCbtSQTzgsVGPh2K-0OwW5m7Q',
    appId: '1:6293016505:ios:1a35086fdbeb65ec23f068',
    messagingSenderId: '6293016505',
    projectId: 'gacha-guard',
    storageBucket: 'gacha-guard.firebasestorage.app',
    iosBundleId: 'com.example.gachaGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9RqDRgPAmWL_MyJQMS-P6yT2vL3jULGk',
    appId: '1:6293016505:web:7f30bf4beef4dae823f068',
    messagingSenderId: '6293016505',
    projectId: 'gacha-guard',
    authDomain: 'gacha-guard.firebaseapp.com',
    storageBucket: 'gacha-guard.firebasestorage.app',
    measurementId: 'G-W7TNPHVJLH',
  );
}
